; syc.ini - Configuración de SYC
; Mismo formato que arc.ini de FreeArc
;
; Secciones:
;   [Compression methods]      -> alias de métodos compuestos
;   [External compressor:name] -> definición de compresor externo

[Compression methods]

; Métodos con xtool + srep + zpaqfranz
xpszf1 = xprecomp+srep:-m5f:-a0+zpaqfranz:-ssd:-t0:-m1
xpszf2 = xprecomp+srep:-m5f:-a0+zpaqfranz:-ssd:-t0:-m2
xpszf3 = xprecomp+srep:-m5f:-a0+zpaqfranz:-ssd:-t0:-m3
xpszf4 = xprecomp+srep:-m5f:-a0+zpaqfranz:-ssd:-t0:-m4
xpszfx = xprecomp+srep:-m5f:-a0+zpaqfranz:-ssd:-t0:-m5

; Métodos con xtool + srep + zpaqfranz
szf1 = srep:-m5f:-a0+zpaqfranz:-ssd:-t0:-m1
szf2 = srep:-m5f:-a0+zpaqfranz:-ssd:-t0:-m2
szf3 = srep:-m5f:-a0+zpaqfranz:-ssd:-t0:-m3
szf4 = srep:-m5f:-a0+zpaqfranz:-ssd:-t0:-m4
szfx = srep:-m5f:-a0+zpaqfranz:-ssd:-t0:-m5


; Definiciones de compresores externos

[External compressor:srep]
header    = 0
packcmd   = compressors\srep.exe {options} $$arcdatafile$$.tmp $$arcpackedfile$$.tmp
unpackcmd = compressors\srep.exe -d $$arcpackedfile$$.tmp $$arcdatafile$$.tmp

[External compressor:xprecomp]
header    = 0
packcmd   = xtool\xtool.exe precomp -mzlib+preflate -c512mb -t100p -d3 -dd $$arcdatafile$$.tmp $$arcpackedfile$$.tmp
unpackcmd = xtool\xtool.exe decode -t75p $$arcpackedfile$$.tmp $$arcdatafile$$.tmp

[External compressor:zpaqfranz]
header     = 0
packcmd    = compressors\zpaqfranz.exe a $$arcpackedfile$$.zpaq $$arcdatafile$$.tmp {options} -nopath
unpackcmd  = compressors\zpaqfranz.exe x $$arcpackedfile$$.zpaq -t0 -space -noeta
packedfile = $$arcpackedfile$$.zpaq